### ISSUE TITLE
프로젝트 생성

### ISSUE THREAD

**Issue by f-lab-robert** [f-lab-edu/Daily#1]
**[ Context ]**
- 프로젝트를 하기 위해서는 생성해야 한다.
- Spring initializer 를 통해 스프링 프로젝트 생성

**Comment by l-lnaln** [comment]
해당 내용으로 결정하였습니다.
![SpringInitializrSetting](https://user-images.githubusercontent.com/87467958/234286471-5cb24ba7-f54e-49cf-b5f1-57f217eb81db.png)

Spring Initializr Setting 결정 과정 정리
https://www.notion.so/Spring-Initializr-Setting-6105739c02f64feeb2c4f567ba2d8d36?pvs=4
