### ISSUE TITLE
Git Branch protection

### ISSUE THREAD

**Issue by f-lab-robert** [f-lab-edu/Daily#11]
1. main branch 에 직접 push X
2. PR 만들고 1명 이상이 승인을 해야만 merge 가능

**Comment by erinleeme** [comment]
Git protection 설정 완료했습니다.
![image](https://github.com/f-lab-edu/Daily/assets/87467958/d985de57-2b81-411a-9194-7dd2ee9f2df8)

**Comment by erinleeme** [comment]
![image](https://github.com/f-lab-edu/Daily/assets/87467958/3166f687-bfbc-47cc-9a9a-c0de03ff3c17)
