### ISSUE TITLE
프로젝트 폴더 구조

### ISSUE THREAD

**Issue by f-lab-robert** [f-lab-edu/Daily#2]
[Context]
- 프로젝트 폴더 구조 후보군 조사 및 결정

**Comment by kwj0318** [comment]
# 프로젝트 디렉토리 구조 


## Application Class
   스프링 공식 문서를 보면 루트 패키지에서 기본 애플리케이션 클래스를 찾을 것을 권장

<br>

## 프로젝트 디렉토리 구성 유형

1) 기능별 구조
    스프링 공식문서에서 말하는 일반적인 구조로 특정 기능과 관련된 모든 클래스가 동일한 패키지에 배치
    기능을 기준으로 분류 했기 때문에 클래스를 찾기가 쉬움
	
    ```
    com
	 +- example
		 +- myapplication
			 +- MyApplication.java
			 |
			 +- customer
			 |   +- Customer.java
			 |   +- CustomerController.java
			 |   +- CustomerService.java
			 |   +- CustomerRepository.java
			 |
			 +- order
				 +- Order.java
				 +- OrderController.java
				 +- OrderService.java
				 +- OrderRepository.java
    ```
<br>	

2) 레이어별 구조
   레이어를 기준으로 클래스를 배치
   프로젝트의 이해도가 낮아도 쉽게 접근할 수 있음

    ```
    com
	 +- gfg
		 +- demo
			 +- MyApplication.java
			 |
			 +- domain
			 |   +- Customer.java
			 |   +- Order.java
			 |
			 +- controllers
			 |     +- OrderController.java
			 |   +- CustomerController.java
			 |
			 +- services
			 |    +- CustomerService.java
			 |    +- OrderService.java
			 |
			 +- repositories
				  +- CustomerRepository.java
				  +- OrderRepository.java    
    ```
	
<br>

3) 도메인별 구조
    각 도메인마다 역할에 맞게 코드를 분리
    관련 코드들이 응집되어 있으나, 프로젝트에 대한 이해가 낮을 경우 전체 구조를 파악하기 어려움
	
	```
	com
	  +- spring
		  +- guide
			  +- ApiApp.java
			  +- domain
		      +-- member
		          +-- api
		          |   +-- MemberApi.java
		          +-- application
		          |   +-- MemberProfileService.java
		          |   +-- MemberSearchService.java
		          |   +-- MemberSignUpRestService.java
		          |   +-- MemberSignUpService.java
		          +-- dao
		          |   +-- MemberFindDao.java
		          |   +-- MemberPredicateExecutor.java
		          |   +-- MemberRepository.java
		          |   +-- MemberSupportRepository.java
		          |   +-- MemberSupportRepositoryImpl.java
		          +-- domain
		          |   +-- Member.java
		          |   +-- ReferralCode.java
		          +-- dto
		          |   +-- MemberExistenceType.java
		          |   +-- MemberProfileUpdate.java
		          |   +-- MemberResponse.java
		          |   +-- SignUpRequest.java
		          +-- exception
		              +-- EmailDuplicateException.java
		              +-- EmailNotFoundException.java
		              +-- MemberNotFoundException.java
	```
	
※ 참고
 - https://docs.spring.io/spring-boot/docs/current/reference/html/using.html#using.structuring-your-code
 - https://stackoverflow.com/questions/40902280/what-is-the-recommended-project-structure-for-spring-boot-rest-projects
 - https://www.geeksforgeeks.org/spring-boot-code-structure/
 - https://stackoverflow.com/questions/64725978/spring-mvc-project-structure
 - https://stackoverflow.com/questions/12397940/spring-and-mvc-proper-project-structure
 - https://studygyaan.com/spring-boot/spring-boot-project-folder-structure-and-best-practices
 - https://www.popit.kr/spring-guide-directory-%EA%B0%80%EC%9D%B4%EB%93%9C/
 
 
 - https://betterprogramming.pub/hexagonal-architecture-with-spring-boot-74e93030eba3
 - https://stackoverflow.com/questions/66971751/layers-in-hexagonal-architecture

**Comment by l-lnaln** [comment]
2번 레이어 구조로 결정
