### ISSUE TITLE
소모임 API

### ISSUE THREAD

**Issue by f-lab-robert** [f-lab-edu/Daily#25]
**[request]**

**[response]**

**Comment by erinleeme** [comment]
# 소모임 등록 API

# Resquest

## Headers

POST HTTP/1.1

Host : [Daily.com](http://daily.com/)

Content-Type : application/json

Content-Length : 00

| Name | Description |
| --- | --- |
| POST | HTTP 메서드 |
|  /meetings | 요청 메세지를 보낼 URL |
| HTTP/1.1 | 프로토콜 정보 |

<br>

## Body

### Parameter

| Name | Type | Descrition | 필수 |
| --- | --- | --- | --- |
| category_id | Integer | 소모임이 속한 카테고리 아이디 | O |
| meeting_name | Long | 등록할 소모임 이름 | O |
| meeting_content | String | 등록할 소모임의 소개 내용 | O |
| meeting_place | String | 등록할 소모임 장소 | O |
| meeting_date | String | 등록할 소모임의 진행 날짜 | O |
| meeting_time | String | 등록할 소모임의 진행 시간 | O |
| meeting_people | Integer | 등록할 소모임의 회원모집수 | O |
| meeting_image | File | 등록할 소모임의 배너이미지 | X |

<br>

### Sample Resquest

```
POST /meetings HTTP/1.1
Host : Daily.com
Content-Type : multipart/form-data; boundary=--------XXX
Content-Length : 00
--------XXX
Content-Disposition: form-data; name="meeting_inform"

{
	category_id : 1,
	meeting_name : "농구하기",
	meeting_content : "함께 농구하면서 건강해져요!",
	meeting_place : "잠실트리지움농구장",
	meeting_date : "2023-6-1",
	meeting_time : "오전 10:00",
	meeting_people : 5,
}
--------XXX
Content-Disposition: form-data; name="file"; filename="example.jpg"
Content-Type: image/jpeg

[파일 데이터]
--------XXX--
```

# Response

## Headers

### StatusLine

```
HTTP/1.1 200 OK
Response Status code -> 200 Ok
content-type : application/json
```

| Name | Description |
| --- | --- |
| HTTP/1.1 | 프로토콜에 대한 정보 |
| 200 OK | 요청의 성공 또는 실패를 나타내는 상태 코드 |

<br>

## Body

### Sample Request

| Name | Description |
| --- | --- |
| result | 요청에 대한 처리 결과 |
| message | 응답 메세지 |

- 성공적으로 등록된 경우

```
{
	result : "success"
	message : "Validation passed"
}
```

### 유효성 검사

- 맞지 않은 이미지 포맷 파일을 첨부했을 시

```
{
	result : "failed"
	message : "Invalid data: The image format is not right"
}
```

- 이미지 용량 제한을 넘었을 시

```
{
	result : "failed"
	message : "Invalid data: Image capacity limit exceeded"
}
```

- 소모임 이름이 글자수 제한을 넘었을 시

```
{
	result : "failed" 
	message : "Invalid data: The name of the small group exceeded the character limit"
}
```

- 소모임 내용이 글자 수 제한이 넘었을 시

```
{
	result : "failed" 
	message : "Invalid data: The content of the small group exceeded the limit of the number of characters"
}
```

- 날짜 포맷이 맞지 않았을 시

```
{
	result : "failed"
	message : "Invalid data: The date format doesn't fit"
}
```

- 시간 포맷이 맞지 않았을 시

```
{
	result : "failed"
	message : "Invalid data: The time format doesn't fit"
}
```

- 필수 값이 입력이 안되어있는 경우

**출처**
[https://developer.mozilla.org/en-US/docs/Web/HTTP/Messages](https://developer.mozilla.org/en-US/docs/Web/HTTP/Messages)
[https://goddaehee.tistory.com/169](https://goddaehee.tistory.com/169)
[https://stackoverflow.com/questions/8659808/how-does-http-file-upload-work](https://stackoverflow.com/questions/8659808/how-does-http-file-upload-work)
