### ISSUE TITLE
DB 모델링

### ISSUE THREAD

**Issue by f-lab-robert** [f-lab-edu/Daily#3]
[Context]
- 기획서가 완성 되었으니 DB 모델링 필요
- ERD 설계

**Comment by l-lnaln** [comment]
# DB 모델링 #
![Daily drawio2](https://user-images.githubusercontent.com/87467958/235986172-88b0863c-f578-485f-af8d-b8c6c87baa31.png)


### DB 모델링 정리 - 구글 시트
https://docs.google.com/spreadsheets/d/1IXrJDQchZMeoLgeSndq4GOQfTSN-3Ku0EBpuWmMIx5w/edit?usp=sharing

**Comment by kwj0318** [comment]
# DB 모델링

![Daily-2](https://user-images.githubusercontent.com/9190171/236609716-e0bfca0d-1acf-4706-b97c-ab6a66b5eb57.png)


## 구글 시트
 - https://docs.google.com/spreadsheets/d/1TxalSVM8bEc1ZEGaW38GKon5UBDR1ksJMKgbtGcqZEQ/edit?usp=sharing

**Comment by kwj0318** [comment]
![Daily](https://github.com/f-lab-edu/Daily/assets/9190171/1e72ac93-46df-4a1a-b2df-72a41f7bc3e7)

**Comment by f-lab-robert** [comment]
createdBy, updatedBy, createdDate, updatedDate

**Comment by f-lab-robert** [comment]
- timestamp vs datetime
- int -> bigint
- unique 설정

**Comment by kwj0318** [comment]
## PK의 데이터타입은 BIGINT vs INT?

<br/>

int 타입의 저장 공간은 4byte로 숫자 범위는 43억까지이고 BIG INT 타입의 저장 공간은 8byte, +- 9,223,372,036,854,775,807 로 거의 무한대에 가까운 범위를 가질 수 있다.

<br/>

  초기에는 대량의 데이터를 다룰일이 없기 때문에 메모리 공간을 덜 차지하는 int를 고려하였으나 추후 확장 성 고려 하여  bigint대신 int를 사용했을때의 성능적인 이슈보다 int의 범위를 초과할때 발생한는 이슈가 더 크다고 판단하여 int를 bigint로 변경

<br/>
  
  ※ 구글 유튜브에서 조회수를 int에서 bigint로 변경한적이 있음
&emsp;    https://youtu.be/oDUdh9Toej4

  

<br/>
참고


&emsp;- https://dev.mysql.com/doc/refman/8.0/en/storage-requirements.html
&emsp;- https://stackoverflow.com/questions/9376610/bigint-mysql-performance-compared-to-int
<br/>

<br/>
<br/>

## DATETIME VS TIMESTAMP

<br/>

1. 크기 및 형식<br/>
DATETIME의 크기는 8byte(MySQL 5.6.4 이후 5byte)로 TIMESTAMP의 크기인 4byte보다 크지만 숫자롤 저장되는 TIMESTAMP와 달리 YYYY-MM-DD HH:MM:SS 라는 형식으로 저장되어있어 사용하기 편리하고 가독성이 좋음       
&emsp;&emsp;- TIMESTAMP : 1684240708
&emsp;&emsp;- DATETIME :  2023-05-16 12:38:43<br/>
    

<br/>    
<br/>


2. 서버 시간에따른 시간 <br/>
DATETIME은 고정된 시간을 사용하지만 TIMESTAMP는 서버 시간에 따라 시간이 유동적이기 때문에 서버 시간을 고려해서 변환해주는 작업이 필요하다. <br/>
&emsp;&emsp;현재 시간 조회<br/>
&emsp;&emsp;&emsp; ![Untitled](https://github.com/f-lab-edu/Daily/assets/9190171/5acdd7bd-e2e7-4936-b8f9-72f36785e90e) <br/>
&emsp;&emsp; system_time_zone 의 시간을 변경하고 현재 시간을 조회<br/>
&emsp;&emsp;&emsp; ![Untitled (1)](https://github.com/f-lab-edu/Daily/assets/9190171/d3fa125e-b371-46b5-9d86-a2876bae2787)
<br/>



3. 날짜 지원범위<br/>
DATETIME은 1000-01-01 00:00:00 ~ 9999-12-31 23:59:59 까지 지원을 하며 TIMESTAMP는 1970-01-01 00:00:01' UTC에서 2038-01-19 03:14:07까지 지원한다.

    - 38년 문제(Y2K38)
    
        대부분의 32비트 컴퓨터에서 초 시간을 저장하는데 사용하는 time_t는 부호있는 32비트 정수형이기 때문에 38년 1월 19일이 넘어가면 부호가 음수로 변경되고 이상 작동을 유발, 64 비트에서는 정상 작동

<br/>
<br/>
Daily 프로젝트에서는 각 지역의 시간대를 고려할 필요 없고 MariaDB에서는 TIMESTAMP의 지원 범위는 2038년까지이기 때문에 DATETIME을 쓰기로 결정
<br/>
<br/>
  
  ※ 구글 캘린더에서 발생했던 TIMESTAMP 문제
&emsp;    https://www.youtube.com/watch?v=Yg0dXH2O_tg




<br/>
<br/>
<br/>
참고

&emsp;- https://dev.mysql.com/doc/refman/8.0/en/datetime.html
&emsp;- https://dev.mysql.com/doc/refman/8.0/en/time-zone-support.html
&emsp;- https://stackoverflow.com/questions/409286/should-i-use-the-datetime-or-timestamp-data-type-in-mysql
&emsp;- https://ko.wikipedia.org/wiki/2038%EB%85%84_%EB%AC%B8%EC%A0%9C

<br/>
<br/>
<br/>
<br/>



## ADMIN

<br/>

현재 모든 계정과 관련된 테이블은 Member테이블에서 enum이란 타입을 이용하여 관리자와 사용자를 구분하고 있지만 추후 확장시  Admin 테이블과 User 테이블을 구분하여 별도로 관리하는 것도 고려 

<br/><br/><br/><br/>
## DB 모델링 최종본

![Daily (1)](https://github.com/f-lab-edu/Daily/assets/9190171/f23266aa-0f48-4efc-a57e-cff18b5bd6a1)
