### ISSUE TITLE
DB 선택

### ISSUE THREAD

**Issue by f-lab-robert** [f-lab-edu/Daily#4]
[Context]
- MYSQL, MariaDB, PostgreSQL 중 선택\

**Comment by kwj0318** [comment]
# MYSQL, MariaDB, PostgreSQL 비교


## MySQL
 - 오라클에서 인수하여 관리하고 있는 RDBMS이다.
 - MySQL을 사용하는 기업은 Facebook, Flickr, Twitter, Wikipedia, YouTube 등이 있다.
 - 커밋, 롤백 및 충돌 복구 기능이 있는 InnoDB 등 다양한 스토리지 엔진을 제공한다.
   - 스토리지 엔진이란 SQL 명령을 인식하고 해석하여 관계형 데이터베이스에 액세스하고 데이터를 조사하는 소프트웨어

   
<br/>
<br/>
&emsp; 참고

&emsp;&emsp;- https://ko.wikipedia.org/wiki/MySQL
&emsp;&emsp;- https://dev.mysql.com/doc/refman/8.0/en/storage-engines.html


<br/>
<br/>
<br/>
<br/>


## MariaDB
 -  MySQL의 포크이며 오픈소스이다.
    - 포크란 하나의 소프트웨어 소스 코드를 통째로 복사하여 독립적인 새로운 소프트웨어를 개발하는 것
 - MySQL에서 제공하는 InnoDB와 같은 스토리지 엔진 이외에 MariaDB에서 추가적으로 다양한 스토리지 엔진을 제공
    - 미제공 하는 스토리지엔진도 있지만 더욱 다양한 엔진을 제공하고 있음 
 - MariaDB를 사용하는 기업은 삼성, Red Hat, NOKIA, 등이 있다.

<br/>
&emsp;참고

&emsp;&emsp;- https://ko.wikipedia.org/wiki/MariaDB
&emsp;&emsp;- https://www.techtarget.com/searchdatamanagement/definition/MariaDB


<br/>
<br/>
<br/>
<br/>


## PostgreSQL
 - 객체지향 관계형 데이터베이스 관리싀스템의 하나이다.
 - PostGIS 와 같은 지리 정보시스템의 보조 프로그램을 지원
 - PostgreSQL을 사용하는 기업은 애플, 인스타그램, 트위치,레딧, 스카이프 등이 있다.

<br/>
&emsp;참고

&emsp;&emsp; - https://ko.wikipedia.org/wiki/PostgreSQL
&emsp;&emsp; - https://www.postgresql.org/about/
&emsp;&emsp; - https://learnsql.com/blog/companies-that-use-postgresql-in-business/
 

<br/>
<br/>
<br/>
<br/>


## MariaDB vs MySQL
 - MariaDB의 스레드 풀링 기능은 무료이지만 MySQL은 유료이다.
 - 옵티마이저를 비교 했을 경우 MariaDB가 최적화 되어있는 부분이 많다.
   - 옵티마이저란 SQL을 빠르고 효율적으로 수행할 최적의 처리 경로를 생성해주는 DBMS 내부의 핵심 엔진
    
    
<br/>
&emsp; 참고

&emsp;&emsp; - https://mariadb.com/kb/en/optimizer-feature-comparison-matrix/
&emsp;&emsp; - https://www.guru99.com/mariadb-vs-mysql.html
&emsp;&emsp; - https://blog.devart.com/mysql-vs-mariadb.html

<br/>
<br/>
<br/>
<br/>



## PostgreSQL vs MariaDB
 - PostgreSQL은 대소문자를 구분한다.
 - MariaDB는 IF, FINULL문을 사용 가능하나 PostgreSQL은 CASE문만 사용 가능하다.
 - PostgreSQL은 멀티 프로세스이고, MariaDB는 멀티 스레드 이다.
   - MariaDB는 복잡한 쿼리에서는 코어를 하나의 CPU만 사용하기 때문에 성능 저하가발생할 수 있다. 
 - MariaDB는 마스터-마스터, 마스터-슬레이브 복제 전략을 제공, PostgreSQL은 a마스터-슬레이브 복제만 지원
   - 마스터-마스터 복제 시 하나의 서버를 사용 할 수 없더라도 다른 서버는 업데이트 가능


<br/>
&emsp; 참고

&emsp;&emsp; - https://www.integrate.io/ko/blog/postgresql-vs-mysql-the-critical-differences-ko/
&emsp;&emsp; - https://docs.oracle.com/cd/E17076_05/html/gsg_txn/C/multithread-intro.html
&emsp;&emsp; - https://hevodata.com/learn/mariadb-vs-postgresql/#par1
&emsp;&emsp; - https://www.integrate.io/ko/blog/which-modern-database-is-right-for-you-ko/
&emsp;&emsp; - https://www.dbvis.com/thetable/a-guide-to-multithreading-in-sql/
&emsp;&emsp; - https://techblog.woowahan.com/6550/

**Comment by l-lnaln** [comment]
# DB 비교 #
MariaDB는 MySQL에서 파생된 DBMS이고 차이점은 MySQL의 유료 버전에서 제공하는 기능 및 추가적으로 제공하는 기능이 있다는 것외에는 크게 없는 것 같아 특징은 MySQL과 PostgreSQL로 비교하였습니다.

---

## 1. DBMS(Database Management System)란?

- 데이터베이스에 접근할 수 있게 하는 시스템을 말한다.
- SQL로 작성된 쿼리를 통해 데이터를 관리할 수 있다.

*SQL(Structured Query Language)는 데이터베이스에 접근하기위해 사용되는 언어이다.

## 2. MySQL

- 관계형 DBMS이다.
- 테이블의 기본 구성 인덱스 구조는 **CLUSTERED INDEX**이다.
    
    ***INDEX란?**
    
    데이터 검색 속도를 향상시켜주는 자료구조이다.
    
    **CLUSTERED INDEX란?**
    
    데이터를 특정 기준으로 정렬시키는 방식이다. 
    
    데이터가 삽입되는 순서와 상관없이 각 테이블의 정렬 기준대로 데이터가 정렬된다.
    
    중간에 새로운 데이터를 추가할 시 다른 데이터들의 인덱스를 변경 후 데이터를 추가한다.
    
    ⇒ 업데이트 작업보다는 읽기 작업에 더 유용한 방식이다.
    
- 기본 트랜잭션 격리 단계는 **REPEATABLE READ** 단계이다.
    
    **REPEATABLE READ란?**
    
    한 트랜잭션 안에서 여러 select를 수행하더라도 값이 변하지 않음을 보장한다. 
    
    **⇒ 여러 select 작업이 수행될 때의 문제점을 보완한 것으로, 읽기 작업 수행 시 사용된다.**
    
- **Undo Segment 방식**을 사용한다.
    
    **Undo Segment 방식이란?** 
    
    수정된 최신 데이터를 기존 데이터에 반영하고 수정되기 전 데이터를 Undo영역이라는 별도의 공간에 저장하여 관리하는 방식이다.
    
- 데이터 타입의 범위는 문자열, 숫자 등과 같이 단순 타입만 제공한다.
- UPDATE 방식이 기존 데이터의 값을 수정하는 방식이다.

**출처**
[https://www.oracle.com/mysql/what-is-mysql/](https://www.oracle.com/mysql/what-is-mysql/)
[https://www.tutorialspoint.com/what-are-the-main-features-of-mysql](https://www.tutorialspoint.com/what-are-the-main-features-of-mysql)
[https://www.javatpoint.com/mysql-features](https://www.javatpoint.com/mysql-features)
[https://intellipaat.com/blog/what-is-mysql/#no8](https://intellipaat.com/blog/what-is-mysql/#no8)
[https://www.jobsity.com/blog/5-reasons-why-mysql-is-still-the-go-to-database-management-system](https://www.jobsity.com/blog/5-reasons-why-mysql-is-still-the-go-to-database-management-system)

## 3. PostgreSQL

- 객체지향 DBMS이다.
    
    테이블 구조가 객체로 다뤄져 테이블끼리의 상속이 가능하다.
    
    → 자식 테이블은 부모 테이블의 열을 받아 사용할 수 있다.
    
    데이터 타입으로 확장이 가능하다.
    
    → 데이터 타입이 기본 데이터 타입으로만 한정되어있지 않다.
    
- 테이블 기본 구성 인덱스 구조로는 **NON-CLUSTERED INDEX** 구조이다.
    
    **NON-CLUSTERED INDEX란?**
    
    데이터가 정렬되어있는 구조가 아닌 노드 형식으로 데이터들이 저장된다.
    
    저장 순서는 데이터 삽입 순서이며 각 노드는 삽입 순서로 구조화된 인덱스와 각 인덱스가 가리키고 있는 데이터의 포인터로 구성되어있다.
    
    데이터를 추가하면 다른 데이터를 건들 필요 없이 추가만 하면 되는 방식이지만,
    
    데이터를 조회할 시에는 각 데이터가 가리키고 있는 포인터를 찾아야하기 때문에 클러스터 구조보다 느릴 수 있다.
    
    **⇒ 업데이트 방식에 더 이점을 보인다.**
    
- 기본 트랜잭션 격리 단계는 **READ COMMITTED** 단계이다.
    
    **READ COMMITTED란?**
    
    커밋이 완료된 데이터에만 접근할 수 있는 수준이다.
    
    **주의할 점**
    
    한 트랜잭션안에 여러 select 작업들이 수행되는 경우 select 작업이 수행될 때마다 다른 트랜잭션에서 커밋한 값으로 가져오기 때문에 다른 값을 가져올 수 있다.
    
- **MGA(Multi Generation Architecture) 방식**으로 관리한다.
    
    **MGA(Multi Generation Architecture) 방식이란?**
    
    데이터를 수정할 때 기존 데이터를 수정하는 것이 아닌 이전 데이터를 삭제하지 않고 새로운 데이터를 추가하는 방식이다.
    
    기존 데이터와 새로운 데이터의 버전을 관리함으로써 구분한다.
    
![Untitled](https://user-images.githubusercontent.com/87467958/235982280-deb6f4c3-1650-42ee-b1ca-ce7305d6285a.png)
 by.이현아
    
- UPDATE 시 UPDATE된 데이터가 새로 추가되고 기존 데이터는 삭제되는 방식이다.
- NOSQL 기능도 지원한다.
    
    ⇒ JSON 타입과 같이 NOSQL에서 지원하는 데이터 타입을 다룰 수 있다.
    

**출처**
[https://www.openlogic.com/blog/postgresql-vs-mysql](https://www.openlogic.com/blog/postgresql-vs-mysql)
[https://www.postgresqltutorial.com/postgresql-getting-started/what-is-postgresql/](https://www.postgresqltutorial.com/postgresql-getting-started/what-is-postgresql/)
[https://aws.amazon.com/ko/rds/postgresql/what-is-postgresql/](https://aws.amazon.com/ko/rds/postgresql/what-is-postgresql/)
[https://kinsta.com/knowledgebase/what-is-postgresql/#when-to-use-postgresql](https://kinsta.com/knowledgebase/what-is-postgresql/#when-to-use-postgresql)
[https://arctype.com/blog/postgresql-features-list/](https://arctype.com/blog/postgresql-features-list/)
[https://www.theserverside.com/blog/Coffee-Talk-Java-News-Stories-and-Opinions/What-is-MVCC-How-does-Multiversion-Concurrencty-Control-work](https://www.theserverside.com/blog/Coffee-Talk-Java-News-Stories-and-Opinions/What-is-MVCC-How-does-Multiversion-Concurrencty-Control-work)
[https://www.edureka.co/community/14151/database-lock-and-its-types](https://www.edureka.co/community/14151/database-lock-and-its-types)
[https://www.geeksforgeeks.org/levels-of-locking-in-dbms/](https://www.geeksforgeeks.org/levels-of-locking-in-dbms/)

## 4. MySQL vs PostgreSQL

|  | MySQL | PostgreSQL |
| --- | --- | --- |
| 공통점 | 관계형 데이터 베이스로 서로 관련된 테이블에 데이터를 저장한다. |  |
|  | 구조화된 쿼리문을 사용하여 데이터에 접근한다. |  |
|  | 오픈소스이다. |  |
| 차이점 | 관계형 데이터 베이스로 데이터들이 테이블과 열과 같이 관계를 이루며 정렬되어있다. | 객체 관계형이기 때문에 데이터들을 객체로 다뤄 상속이 가능하며 객체를 데이터 타입으로 지정할 수 있다. ⇒ 객체로 다룰 수 있음으로써 방대한 양의 데이터들을 관리하기에 MySQL보다 유연하다. |
|  | 구조화된 쿼리문만 사용이 가능하다. | NOSQL기능을 지원함으로써 구조화되어있지 않은 쿼리문을 사용할 수 있다. ⇒   구조화되어있지 않는 쿼리문을 사용함으로써 즉, 작업을 수행할 때마다 정해진 쿼리 문법에 매번 맞출 필요가 없기 때문에 다양한 작업을 수행할 때 편리하다. |
|  | 클러스터 구조로 데이터들을 조회하는데는 PostgreSQL보다 빠르다. | 비클러스터 구조로 데이터들을 업데이트하고 삭제하는데 MySQL보다 빠르다. |

**⇒ PostgreSQL은 방대한 데이터를 가지고 동시적으로 많은 작업들을 수행하는데 적합한 것 같다.

Daily 프로젝트에서는 방대한 데이터를 다룬다기보단 어느정도 정해진 양의 데이터를 다룰 예정이고 NoSQL을 다룰 일은 없기 때문에 PostgreSQL보단 MySQL이 적합한 것 같다.**

**출처**
[https://www.integrate.io/ko/blog/postgresql-vs-mysql-the-critical-differences-ko/](https://www.integrate.io/ko/blog/postgresql-vs-mysql-the-critical-differences-ko/)
[https://www.openlogic.com/blog/postgresql-vs-mysql](https://www.openlogic.com/blog/postgresql-vs-mysql)
[https://aws.amazon.com/ko/compare/the-difference-between-mysql-vs-postgresql/](https://aws.amazon.com/ko/compare/the-difference-between-mysql-vs-postgresql/)
[[https://hanamon.kr/데이터베이스-sql-vs-nosql/](https://hanamon.kr/%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%B2%A0%EC%9D%B4%EC%8A%A4-sql-vs-nosql/)](https://hanamon.kr/%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%B2%A0%EC%9D%B4%EC%8A%A4-sql-vs-nosql/)

## 5. MySQL vs MariaDB

MariaDB가 MySQL보다 더 많은 스토리지 엔진을 사용함으로써 속도가 더 빠르며 더 많은 기능을 제공하고 있다.

- [https://mariadb.com/kb/en/incompatibilities-and-feature-differences-between-mariadb-10-7-and-mysql-8-/](https://mariadb.com/kb/en/incompatibilities-and-feature-differences-between-mariadb-10-7-and-mysql-8-/)

MySQL의 데이터 추가 작업의 속도가 느린점을 개선하였다.

**⇒ MySQL이 MariaDB보다 훨씬 전부터 이용되었던거라 많은 곳에서 사용되고 있고 문서들도 많지만 MariaDB는 MySQL기반의 MySQL의 부족했던 부분을 개선하여 나온 DBMS이기 때문에 둘중에서는 MariaDB를 사용하는 것이 적합할 것 같다.**

**출처**
[https://www.cloudways.com/blog/mariadb-vs-mysql/#mariadb-vs-mysql](https://www.cloudways.com/blog/mariadb-vs-mysql/#mariadb-vs-mysql)
[https://www.guru99.com/mariadb-vs-mysql.html](https://www.guru99.com/mariadb-vs-mysql.html)
[https://blog.purestorage.com/purely-informational/mysql-vs-mariadb/](https://blog.purestorage.com/purely-informational/mysql-vs-mariadb/)
[https://mariadb.com/kb/en/incompatibilities-and-feature-differences-between-mariadb-10-7-and-mysql-8-/](https://mariadb.com/kb/en/incompatibilities-and-feature-differences-between-mariadb-10-7-and-mysql-8-/)

**Comment by l-lnaln** [comment]
DB 결론 링크 올립니다.
https://sharp-candytuft-cd2.notion.site/DB-41e60af1dc5b49719848ce54c79c4350
