### ISSUE TITLE
Spring Security 학습

### ISSUE THREAD

**Issue by erinleeme** [f-lab-edu/Daily#44]
개인 Repository 를 만들고 Spring Security 를 통해 Session 방식으로 로그인을 구현하는 로직 구현

### Spring Security 로그인 구현
Session : https://github.com/erinleeme/springsecurity-test/tree/session
JWT : https://github.com/erinleeme/springsecurity-test/tree/security-token

**Comment by erinleeme** [comment]
# Spring Security

## 1. Spring Security란?

Spring에서 제공하는 사용자 정의, 사용자 권한 부여 등 접근에 관한 제어 기능을 제공하는 프레임워크로 Bcrypt 암호화 알고리즘을 사용한다.

### Bcrypt 알고리즘이란?

슬로우 해싱(Slow Hashing)과 솔팅(Salting) 기법을 사용하는 단방향 알고리즘이다.

- 슬로우 해싱은 말그대로 해싱 작업 시간을 지연시켜 무차별 해싱 공격을 막는 기법이다.
    
    모든 가능한 조합을 사용하여 무차별적으로 해싱하여 암호화 알고리즘을 찾아내는 공격에 강하다.
    
- 솔팅 기법은 Bcrypt 알고리즘으로 만들어진 해시에 추가로 무작위의 문자열을 추가하여 새로운 솔트값을 저장하는 기법이다.

비밀번호 데이터를 Bcrypt 알고리즘을 통해 저장 시 솔팅 기법으로 인해 비밀번호 해시값과 솔트값이 함께 저장되며 후에 비밀번호 검증 시에는 솔트값이 사용된다.

해시값에 추가로 무작위한 문자열이 같이 저장되기 때문에 해시 알고리즘을 알아낸다해도 원본 데이터까지 공개되지 않는다.

<br>

## 2. Spring Security 동작 원리

기존 클라이언트가 요청 메세지를 보냈을 때 서버까지 전달되는 과정은 다음과 같다.
![1](https://github.com/f-lab-edu/Daily/assets/87467958/26bcaedb-851c-48e4-8b48-372e3b490e23)
https://docs.spring.io/spring-security/reference/servlet/architecture.html

### 클라이언트 - 서버

1. 클라이언트가 요청을 보낸다.
2. 보낸 요청은 웹 컨테이너에 도달하고 가장 먼저 여러 필터가 연결되어있는 필터 체인에 도달한다.
3. 필터 체인에 있는 필터 조건들을 거치며 최종 통과한 요청 데이터는 스프링 서블릿 컨테이너에 도달한다.
4. 스프링 컨테이너의 디스패처 서블릿은 요청을 받아 요청을 처리할 컨트롤러를 찾는다.
5. 인터셉터가 있다면 컨트롤러에 전달되기 전 작업을 수행 후 담당 컨트롤러에게 전달한다.
6. 후에 서버로부터 다시 클라이언트에 응답 메세지가 도달하는 데까지는 동일하게 인터셉터와 필터를 거치고 전달된다.

### 클라이언트 - 스프링시큐리티 - 서버

이때 Spring Security를 적용하면 Fileter 체인에 새로운 시큐리티 체인을 추가한다.
![2](https://github.com/f-lab-edu/Daily/assets/87467958/7cb89a52-8617-4d3a-98c1-edee2a5bd1ba)
https://docs.spring.io/spring-security/reference/servlet/architecture.html

1. Spring Security는 DelegatingFilterProxy 라는 필터를 만들어 메인 Filter Chain 사이에 추가된다.
2. DelegatingFilterProxy에 FilterChainProxy를 통해 SecurityFilterChain과 매핑
    
    ### 이 과정이 필요한 이유?
    
     **Filter 처리는 웹 컨테이너에서 처리되는 것이기 때문에 Spring Bean 컨테이너에 접근할 수 없다. 그렇다면 어떻게 스프링 시큐리티 필터가 적용되는 것일까?**
    
    웹 컨테이너에서 스프링 빈 컨테이너를 연결해주는 것이 바로 **DelegatingFilterProxy**이다.
    
    ⇒ DelegatingFilterProxy는 스프링 컨테이너와 연결하여 스프링 시큐리티 필터 역할을 하는 SecurityFilterChain을 찾아 요청 데이터를 넘겨주고 SecurityFilterChain은 시큐리티 필터 작업을 수행할 수 있게 되는 것이다.
![3](https://github.com/f-lab-edu/Daily/assets/87467958/77ca2004-c892-4d87-90aa-0a258a588d3b)
    https://catsbi.oopy.io/f9b0d83c-4775-47da-9c81-2261851fe0d0

<br>
    
  ### 정리
    
    **⇒ DelegatingFilterProxy는 받은 요청을 서블릿 필터 역할을 하는 스프링 시큐리티 빈인 FilterChainProxy에게 전달**
    
    **⇒ FilterChainProxy 빈은 SpringSecurityFilterChain 필터를 가지고 차례대로 인증 작업 수행**
    
3. 인증 및 인가 작업이 수행된 후 최종 통과한 요청 데이터만 스프링 서블릿 컨테이너에 도달하게 된다.
    - 인증(Authentication)
    
    인증은 사용자가 접근 권한이 있는지에 대해 검증하는 단계로 **SecurityContextHolder 클래스**를 통해 검증된다.
    
    SecurityContextHolder 클래스는 검증된 사용자에 대한 정보가 저장되는 곳으로 어떠한 사용자가 접근하면 먼저 SecurityContextHolder통해 검증된 사용자인지 확인한다.
    
    - 인가(Authentication)
    
    검증이 완료되면 가장 마지막으로 AuthorizationFilter를 통해 접근을 승인하는 단계이다.
    
    인가 결과로 요청을 처리한다.

**Comment by erinleeme** [comment]
개인 레퍼지토리 주소
https://github.com/erinleeme/springsecurity-test

**Comment by kwj0318** [comment]
# Spring Sequrity

- 인증, 권한 부여 및 보안 기능을 제공하는 프레임 워크이다. 


    

![image](https://github.com/f-lab-edu/Daily/assets/9190171/d34fa60a-a7f3-432d-819b-bd89fe18e08a)
    

DelegatingFilterProxy는 Servlet 컨테이너의 라이프 사이클과 스프링의 ApplicationContext를 연결하여 빈으로 구성된 필터를 Servlet 컨테이너가 이용할수 있게 한다.
    
SecurityFilterChain은 DelegatingFilterProxy 내에 있는 FilterChainProxy에서 어떤 요청에 대해 어떤 Spring Security Filter 인스턴스를 호출해야 하는지 결정하는데 사용 된다.
    

- 인증(**Authentication**)
    
    - SecurityContexHoder는 누가 인증이 되었는지에 대한 세부 정보를 저장하는 곳이며 SecurityContext에서 현재 사용자의 인증 및 권한 정보를 유지 및 관리한다.
    
    - AuthenticationManager를 이용하여 입력이 유효한지 확인할 수 있으며 값이 유효하지 않으면 AuthenticationException이 발생한다 
    
- 권한 (**Authorization**)
    - 인증 완료 후 특정 작업이나 작업을 수행하도록 허용하는 프로세스를 작동 시킵니다
    - 메서드 호출 또는 웹 요청과 같은 보안 개체에 대한 액세스를 제어하는 인터셉터를 제공하며 **AuthorizationManager**를 통하여 호출을 결정 할 수있다.
    - GrantedAuthority를 이용하여 사용자가 가지는 권한을 확인할 수 있으며 000는

**Comment by erinleeme** [comment]
JWT 정리

https://github.com/f-lab-edu/Daily/wiki/Spring-Security-%E2%80%90-JWT

**Comment by erinleeme** [comment]
# Spring Security 인증 아키텍처

![4](https://github.com/f-lab-edu/Daily/assets/87467958/ca46f543-a783-4df5-8210-07fef48c80f9)

1. 클라이언트로 요청이 들어오면 AuthenticationFilter를 거치고 요청 메세지에 담긴 아이디와 비밀번호를 기반으로 UserPasswordAuthenticationToken을 발급해준다.
2. 발급한 UserPasswordToken을 Authentication Manager로 전달한다.
3. Authentication Manager에서 실제 인증을 처리하는 AuthenticatioProvider로 전달되고 UserDetailsService를 통해 인증 처리가 이뤄진다.
4. UserDetailsService에서는 전달받은 사용자의 ID로 DB에 있는 계정인지 조회 후 조회한 결과를 반환한다.
5. 인증이 성공된 UserPasswordToken은 다시 AuthenticationManager → AuthenticationFilter까지 전달되고 SecurityContextHolder에 저장된다. 

# AuthenticationManager / AuthenticationProvider

스프링 시큐리티에는 여러가지 필터들이 있는데 JWT 같은 것들을 사용하기 위해선 필터를 커스텀해야한다. 

커스틈 필터를 만들 때 필요한 필터 규약들이다.

## AuthenticationManager

전달받은 객체를 권한이 있는지 인증을 처리하는 방법을 정의하는 인터페이스이다.

AuthenticationFilter 를 통해서 동작되며 인증에 성공한 Authentication 객체를 반환하여 SecurityContextHandler로 전달하여 저장되게 한다.

## AuthenticationProvider

AuthenticationManager로부터 받은 사용자 데이터를 가지고 실질적인 인증 처리를 수행하는 클래스이다.

전달받은 객체가 인증에 성공한 객체인지 아닌지에 대한 검사를 수행한다.

![5](https://github.com/f-lab-edu/Daily/assets/87467958/eba8efda-7e18-4ff1-a4de-602d994b1f54)

**Comment by kwj0318** [comment]
[Session Login Test]
https://github.com/kwj0318/spring-security-session-login-test
