### ISSUE TITLE
로그인 API

### ISSUE THREAD

**Issue by f-lab-robert** [f-lab-edu/Daily#50]

**Comment by erinleeme** [comment]
# 로그인 API
## [Request]
### Headers
```
POST HTTP/1.1
Host: Daily.com
Content-Type: application/json
Content-Length: 00
```
| Name | Description |
| --- | --- |
| POST | HTTP 메서드 |
|  /login
| 요청 대상 |
| HTTP/1.1 | 프로토콜 정보 |

### Body

**Parameter**
| Name | Type | Descrition | 필수 |
| --- | --- | --- | --- |
| email | String | 이메일 | O |
| password | String | 비밀번호 | O |


<br>

### Sample Resquest

```
POST  /login HTTP/1.1
Host: Daily.com
Content-Type: application/json; 
Content-Length: 00
{
	"email": "test1025@email.com",
	"password": "test1025#",
}

```

## [Response]

### Headers

**StatusLine**

```
HTTP/1.1 200 OK
Response Status code -> 200 Ok
content-type : application/json
```

| Name | Description |
| --- | --- |
| HTTP/1.1 | 프로토콜에 대한 정보 |
| 200 | 요청의 성공 또는 실패를 나타내는 상태 코드 |
| OK | 이유 문구 |

<br>

### Body

| Name | Description |
| --- | --- |
| code | 에러 코드 |
| message | 에러 메세지 |

## Sample Response

- 회원 로그인 성공  
```
HTTP/1.1 201 OK
Content-Type: application/json; chartset=UTF-8    
{
   result : "success"
}
 ```
    

- 이메일이 확인되지 않는 경우
```
HTTP/1.1 400 bad_request
Content-Type: application/json; chartset=UTF-8
{
    code : 900
    message : "유효하지 않는 Email입니다."
}
```
    

- 유효성 검사 실패 (이메일 양식이 맞지 않을 경우)
```
HTTP/1.1 400 bad_request
Content-Type: application/json; chartset=UTF-8
    
 {
    code: 400
    message : "이메일 형식이 올바르지 않습니다."
}
```
    

- 유효성 검사 실패 (비밀번호 양식에 맞지 않을 경우)    
```
HTTP/1.1 400 bad_request
Content-Type: application/json; chartset=UTF-8   
{
    code : 400
    message : "비밀번호 형식이 올바르지 않습니다."
}
```
    

- 유효성 검사 실패 (필수 값이 없는 경우)
```
HTTP/1.1 400 bad_request
Content-Type: application/json; chartset=UTF-8
{
    code : 400
    message : "필수값입니다. 다시 입력해주세요"
}
 ```
