### ISSUE TITLE
회원가입 API

### ISSUE THREAD

**Issue by f-lab-robert** [f-lab-edu/Daily#51]

**Comment by erinleeme** [comment]
# 회원가입 API
## [Request]
### Headers
```
POST HTTP/1.1
Host: Daily.com
Content-Type: application/json
Content-Length: 00
```
| Name | Description |
| --- | --- |
| POST | HTTP 메서드 |
|  /members
| 요청 대상 |
| HTTP/1.1 | 프로토콜 정보 |

### Body

**Parameter**
| Name | Type | Descrition | 필수 |
| --- | --- | --- | --- |
| email | String | 이메일 | O |
| password | String | 비밀번호 | O |
| nickname | String | 닉네임 | O |
| member_type | String | 멤버권한 | O |


<br>

### Sample Resquest

```
POST  /meeting/1 HTTP/1.1
Host: Daily.com
Content-Type: application/json; 
Content-Length: 00
{
	"email": "test1025@email.com",
	"password": "test1025#",
	"nickname": "1025",
	"member_type": "USER"
}

```

## [Response]

### Headers

**StatusLine**

```
HTTP/1.1 200 OK
Response Status code -> 200 Ok
content-type : application/json
```

| Name | Description |
| --- | --- |
| HTTP/1.1 | 프로토콜에 대한 정보 |
| 200 | 요청의 성공 또는 실패를 나타내는 상태 코드 |
| OK | 이유 문구 |

<br>

### Body

| Name | Description |
| --- | --- |
| code | 에러 코드 |
| message | 에러 메세지 |

## Sample Response

- 멤버 생성 성공
    
    ```
    HTTP/1.1 201 Created
    Content-Type: application/json; chartset=UTF-8
    
    {
    	result : "success"
    }
    ```
    

- 이메일 중복
    
    ```
    HTTP/1.1 400 bad_request
    Content-Type: application/json; chartset=UTF-8
    
    {
    	code : 901
    	message : "중복된 이메일 입니다."
    }
    ```
    

- 유효성 검사 실패 (이메일 양식이 맞지 않을 경우)
    
    ```
    HTTP/1.1 400 bad_request
    Content-Type: application/json; chartset=UTF-8
    
    {
    	code: 400
    	message : "이메일 형식이 올바르지 않습니다."
    }
    ```
    

- 유효성 검사 실패 (비밀번호 양식에 맞지 않을 경우)
    
    ```
    HTTP/1.1 400 bad_request
    Content-Type: application/json; chartset=UTF-8
    
    {
    	code : 400
    	message : "비밀번호 형식이 올바르지 않습니다."
    }
    ```
    

- 유효성 검사 실패 (필수 값이 없는 경우)
    
    ```
    HTTP/1.1 400 bad_request
    Content-Type: application/json; chartset=UTF-8
    
    {
    	code : 400
    	message : "필수값입니다. 다시 입력해주세요"
    }
    ```
    

- 서버 에러
    
    ```
    HTTP/1.1 500 internal_server_error
    Content-Type: application/json; chartset=UTF-8
    
    {
    	code : 400
    	message : "중복된 이메일 입니다."
    }
    ```
