### ISSUE TITLE
REST API 학습

### ISSUE THREAD

**Issue by f-lab-robert** [f-lab-edu/Daily#7]

**Comment by f-lab-robert** [comment]
https://github.com/f-lab-edu/Daily/issues/12

**Comment by erinleeme** [comment]
# REST API

## API(Application Programming Interface)란?

여러 소프트웨어, 컴퓨터들끼리 데이터를 주고받을 때 지켜야할 프로토콜이다.

데이터를 올바르게 주고 받기 위해서는 API에 맞게 이행해야한다.
<br>

## REST API(Representational State Transfer API)란?

컴퓨터들간 서로의 데이터를 사용하기 위해 접근할 때 HTTP 메서드와 URI를 통해 데이터에 접근하는 작업을 표시하는 REST 방식을 따르는 API이다.

![1](https://github.com/f-lab-edu/Daily/assets/87467958/3bc2ede1-cf02-4c7f-b18c-db5be9dcac69)
[https://velog.io/@yhko1992/REST-API에-대해-설명해보자](https://velog.io/@yhko1992/REST-API%EC%97%90-%EB%8C%80%ED%95%B4-%EC%84%A4%EB%AA%85%ED%95%B4%EB%B3%B4%EC%9E%90)
<br>
## REST 방식이란?

직역을 하면 자원의 상태를 표현하여 클라이언트와 서버 사이에서 데이터를 전달되는 과정에서 정확하게 전송하기 위해 짜여진 아키텍처이다.

## REST 디자인 원칙 6가지

### 균일한 인터페이스

어디서 요청이 오든 상관없이 동일한 요청에는 동일한 응답을 보내야한다.

동일한 요청을 보낼 때 모두 균일하게 동일한 데이터들을 담아 보내는 것을 보장해야 한다. 

### 클라이언트 - 서버 아키텍처

클라이언트와 서버가 완전히 독립적으로 구분되어 있는 구조이다.

클라이언트에서는 서버의 DB와 연결될 수 없고 서버도 클라이언트의 사용자 인터페이스 작업에 관여할 수 없다.

클라이언트가 알아야하는 정보와 서버에서 다루는 정보는 독립적으로 서로의 데이터들에 접근하여 수정할 수 없어야한다.

### Stateless

REST API에서는 서버의 세션이 필요없기 때문에 서버가 클라이언트의 요청과 관련된 데이터를 저장할 수 없다.

### 캐싱 가능성

클라이언트와 서버는 데이터에 대한 캐싱이 가능하기 때문에 응답을 보낼 때는 캐싱 가능여부와 캐시의 유효 기간에 대한 정보를 담아서 보내야 한다.

→ 캐싱이 가능한 경우, 동일한 데이터들이 필요한 경우 서버에 반복적인 요청을 보내지 않고도 클라이언트는 데이터를 사용할 수 있다.

### 계층 구조 아키텍처

데이터의 요청과 응답이 전송될 때는 서로 다른 계층 구조를 통과한다.

즉 서버와 클라이언트가 직접적으로 요청과 응답을 주고받지 않으며 각각의 계층도 서로 상호작용하는 계층에만 접근할 수 있고 그 외 계층에는 접근할 수 없다.

### 코드 온디맨드

옵션 원칙으로 REST API에서는 일반적으로 정적 데이터를 주고받지만 특수한 환경에서는 실행 코드 자체를 포함할 수도 있다.

<br> 

## REST API 특징

- URI를 통해서 데이터에 대한 작업을 정의한다.
    
    이때 URI 구성은 동사를 사용하지 않는다.
    
    **URI(Uniform Resource Identifier)란?**
    
    인터넷 상에서 특정 자원(파일)을 나타내는 주소이다.
    
    **URI 구조**
    
    <aside>
    💡 SCHEMA ://host[:port][/path][?query]
    
    </aside>
    
    schema : http, ftp 등등에 대한 프로토콜의 방식을 담는다.
    
    host : IP 주소
    
    port : 생략됨
    
    ```
    예시 : https://www.naver.com/
    ```
    
- GET, POST, PUT, DELETE와 같이 HTTP 메서드를 사용하여 자원에 대한 작업 처리 요청을 표현한다.
    - GET : 서버에 저장되어있는 데이터를 읽어오는 요청을 보낸다.
    - HEAD : 서버로부터 데이터를 읽어오지 않고 요청 데이터의 존재 유무 확인 요청만 한다.
    - PUT : 데이터가 서버로 전송 시에 서버가 요청의 Body 부분까지 확인하여 Body 데이터까지 서버에 저장하는 요청을 보낸다.
    - POST : Put과 동일하게 서버가 요청의 Body 부분을 확인하는 메서드로 서버에ㅜ 데이터를 보내는 요청이다.
    - DELETE : 지정된 데이터를 삭제하는 요청을 보내는 메서드이다.
    
    ### GET vs POST
    
    GET 요청과 POST 요청 모두 데이터를 서버에 제공하는 메서드이다. 
    
    하지만 각각의 메서드 특징으로 인해 사용되는 경우가 다르다.
    
    | GET | POST |
    | --- | --- |
    | 서버에 보내는 데이터를 URL에 담아 전송하기 때문에 브라우저에 기록이 남는다. | URL에 보내는 데이터를 담지 않는 방식이기 때문에 브라우저에 기록이 남지 않는다. |
    | URL에 담아 보내기 때문에 보내는 데이터의 길이에 제한이 있다. | 파일 업로드와 같이 GET 요청보다 더 다양하게 데이터를 서버로 보낼 수 있다. |
    | 브라우저 캐시에 저장되기 때문에 동일한 작업인 경우에는 서버까지 요청할 필요가 없다. | 브라우저 캐시에 저장되지 않기 때문에 요청때마다 데이터를 서버에 접근해야한다. |
    
    GET은 URI에 전송하는 데이터가 담기기 때문에 정보가 노출되고 브라우저 기록에 다 남기 때문에 데이터에 쉽게 접근이 가능하여 보안상 POST에 비해 덜 안전하다.
    
    그렇기 때문에 데이터를 전송하는 작업에는 GET 방식을 사용하지 않고 서버로부터 가져오는 경우에만 사용되는 것이다.
    

**⇒  클라이언트에서 HTTP 메서드와 지정한 URI를 통해 요청을 보내면 서버에서 받아 작업을 처리하도록 한다.**

### - REST API의 장단점
    
    왜 사용할까?
    
    - 직접 개발을 하지 않은 개발자도 자원을 정의하고 자원을 어떻게 처리해야할지 추상화시킴으로써 간단 명료하게 작업에 대해서 전달할 수  있다.
    - 정해진 규약으로 인해 별도로 API를 만들 필요가 없다.
    - HTTP 프로토콜 기반으로 짜져있기 때문에 많은 플랫폼 서비스에서 적용이 가능하다.
    - 서버와 클라이언트간의 구분이 명확하게 되어있다.
    - 다른 API 아키텍처보다 XML, YAML, JSON 등의 더 다양한 형식들을 지원한다.
    
    단점은?
    
    HTTP 메서드 기반으로 사용할 수 있는 메서드가 제한적이다.
    
    Rete Limits : 초당 15개의 요청만 보낼 수 있으며 그 이상의 요청 속도는 제한한다. 만약 넘어가면 429 오류를 반환한다고 한다.
    
<br>

## REST API 구성요소

![2](https://github.com/f-lab-edu/Daily/assets/87467958/61e6916c-8d87-4395-acda-daf8c31ab694)
[https://www.slideteam.net/rest-api-architecture-php-model-for-data-transfer.html](https://www.slideteam.net/rest-api-architecture-php-model-for-data-transfer.html)

### 자원 : URI

자원을 가리키는 내용을 포함한다.

### 행위 : HTTP 메서드

자원을 다룰 작업을 포함한다.

### 표현

자원이 표현될 JSON, XML, TEXT 등과 같은 방식을 담고 있다.
<br>
<br>

**출처**
[https://aws.amazon.com/ko/what-is/restful-api/](https://aws.amazon.com/ko/what-is/restful-api/)
[https://www.redhat.com/en/topics/api/what-is-a-rest-api](https://www.redhat.com/en/topics/api/what-is-a-rest-api)
[https://www.youtube.com/watch?v=Nxi8Ur89Akw](https://www.youtube.com/watch?v=Nxi8Ur89Akw)
[https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods)
[https://www.rfc-editor.org/rfc/rfc9110#GET](https://www.rfc-editor.org/rfc/rfc9110#GET)
[https://www.diffen.com/difference/GET-vs-POST-HTTP-Requests](https://www.diffen.com/difference/GET-vs-POST-HTTP-Requests)
[https://www.guru99.com/difference-get-post-http.html](https://www.guru99.com/difference-get-post-http.html)
[https://www.ibm.com/kr-ko/topics/rest-apis](https://www.ibm.com/kr-ko/topics/rest-apis)
[https://appmaster.io/ko/blog/rest-apiran-mueosimyeo-dareun-yuhyeonggwa-eoddeohge-dareungayo](https://appmaster.io/ko/blog/rest-apiran-mueosimyeo-dareun-yuhyeonggwa-eoddeohge-dareungayo)
[https://www.integrate.io/blog/why-you-need-a-rest-api/](https://www.integrate.io/blog/why-you-need-a-rest-api/)
[https://spring.io/guides/tutorials/rest/](https://spring.io/guides/tutorials/rest/)
[https://support.thinkific.dev/hc/en-us/articles/4422684774935-REST-API-Rate-Limits](https://support.thinkific.dev/hc/en-us/articles/4422684774935-REST-API-Rate-Limits)
[https://developers.aprimo.com/marketing-operations/rest-api/rate-limits/](https://developers.aprimo.com/marketing-operations/rest-api/rate-limits/)
[https://docs.illumio.com/asp/19.3/Content/Guides/rest-api/overview/rest-api-limits.htm](https://docs.illumio.com/asp/19.3/Content/Guides/rest-api/overview/rest-api-limits.htm)

**Comment by kwj0318** [comment]
# REST API

## REST API 란?

- HTTP 요청을 사용하여 데이터에 엑세스하고 사용하는 어플리케이션 프로그램 인터페이스의 아키텍처 스타일

## API 란?

- application programming interface의 약자로 다른 소프트웨어와 통신을 하기 위해 제공되는 인터페이스

## REST

- Representational State Transfer 의 약자로 웹 서비스를 생성하는 데 사용되는 일련의 규칙을 정의하는 소프트웨어 아키텍처이며 RESTful 이라고도 불린다.

## REST API 특징

### 클라이언트- 서버 아키텍처

- 사용자 인터페이스를 다루는 클라이언트와 와 데이터 저장문제를 다루는 서버의 관심사를 분리한 구조로 두 구성 요소들을 독립적으로 개발 및 유지관리 할 수 있다.

## ****Statelessness****

- 서비스가 사용자 세션을 유지할 필요가 없어야 한다.
- 서버는 클라이언트 세션에 대한 상태를 서버 측에 저장하지 않기 때문에 클라이언트에서 서버로 요청을 할때에 필요한 모든 정보를 입력해야 한다.

### 캐시 가능성

- 캐싱을 지원된다.
- 서버가 각 요청에 대해 동일한 응답을 생성할 필요가 없으므로 서버의 부하가 줄어들고 성능이 향상된다.

### 계층화된 시스템

- 계층화된 시스템 (여러계의 Layer로 구성)으로 설계가 되어야 한다.
- 클라이언트가 중재자를 거치지 않고 서버를 직접 호출 하면 안된다.

### ****Code-On-Demand****

- 유일한 선택 사항 제약조건이다.
- 클라이언트 소프트웨어의 요청에 따라 서버 컴퓨터에서 클라이언트 컴퓨터로 실행 가능한 소프트웨어 코드를 보내는 기술

### 통일된 인터페이스

- 장치, 응용 프로그램 유형에 관계 없이 동일한 리소스에 대한 모든 api 쿼리는 모두 동일하게 보여야 한다.

## REST API 유형

- GET
    - 서버에서 정보를 가져오기 위해 사용하며 일반적으로 검색을 하는데 사용
- POST
    - 서버에 정보를 전송할때 사용하며 새 리소스를 생성하거나 기존 리소스를 업데이트 하는데 사용
- PUT
    - 기존 리소스를 업데이트 하는데 사용
    
- DELETE
    - 리소스를 삭제 할 때 사용

## GET vs POST

- GET은 요청 매개변수가 URL에 포함되기 때문에 보안이 필요하지 않는 데이터를 사용
    
    POST는 body에 저장이 되기 때문에 보안이 필요한 데이터를 사용할 때 적합
    
- GET 요청은 브라우저 히스토리, 캐시 메모리에 저장되고 북마크로 저장이 가능하나  POST는 저장되지 않는다.
- GET은 문자열 데이터만 지원하지만 POST는 다양한 데이터 유형을 지원

## POST vs PUT

- PUT을 여러번 호출할 경우 동일한 결과값이 제공 되지만 POST를 여러번 호출할 경우 다른 결과값이 발생 할 수 있다. (PUT은 멱등적 - 여러 번 적용하더라도 결과가 달라지지 않는 성질)

# URL vs  URI

- URI는 리소스나 이름을 식별하는 데 사용되는 텍스트로서 식별번호를 나타내는 URN과 자원을 검색하기 위한 위치와 프로토콜이을 가지고 있는 URL을 모두 포함한 상위 개념으로 체계, 권한, 경로 및 쿼리와 같은 구성 요소가 포함된다.

![image](https://github.com/f-lab-edu/Daily/assets/9190171/73097e78-3d5e-464d-91c7-9d3e4728643c)

※ 참고

- [https://www.scrapingbee.com/blog/six-characteristics-of-rest-api/](https://www.scrapingbee.com/blog/six-characteristics-of-rest-api/)
- [https://ko.wikipedia.org/wiki/REST](https://ko.wikipedia.org/wiki/REST)
- [https://restfulapi.net/](https://restfulapi.net/)
- [https://www.akana.com/blog/what-is-rest-api](https://www.akana.com/blog/what-is-rest-api)
- [https://www.knowledgehut.com/blog/programming/rest-api](https://www.knowledgehut.com/blog/programming/rest-api)
- [https://www.comunicacionesindustrialeslogitek.com/en/features-of-rest-services/](https://www.comunicacionesindustrialeslogitek.com/en/features-of-rest-services/)
- [https://restfulapi.net/statelessness/](https://restfulapi.net/statelessness/)
- [https://www.javaguides.net/2018/06/rest-architectural-constraints.html](https://www.javaguides.net/2018/06/rest-architectural-constraints.html)
- [https://restapilinks.com/client-server/](https://restapilinks.com/client-server/)
- [https://restapilinks.com/layered-system/](https://restapilinks.com/layered-system/)
- [https://www.csharpstar.com/rest-constraints/](https://www.csharpstar.com/rest-constraints/)
- [https://en.wikipedia.org/wiki/Code_on_demand](https://en.wikipedia.org/wiki/Code_on_demand)
- [https://en.wikipedia.org/wiki/Representational_state_transfer](https://en.wikipedia.org/wiki/Representational_state_transfer)
- [https://javarevisited.blogspot.com/2016/10/difference-between-put-and-post-in-restful-web-service.html#axzz82EJoTC5I](https://javarevisited.blogspot.com/2016/10/difference-between-put-and-post-in-restful-web-service.html#axzz82EJoTC5I)
- [https://stackoverflow.com/questions/7016785/is-put-delete-idempotent-with-rest-automatic](https://stackoverflow.com/questions/7016785/is-put-delete-idempotent-with-rest-automatic)
- [https://stackoverflow.com/questions/630453/what-is-the-difference-between-post-and-put-in-http](https://stackoverflow.com/questions/630453/what-is-the-difference-between-post-and-put-in-http)
- [https://site.financialmodelingprep.com/education/api-endpoint](https://site.financialmodelingprep.com/education/api-endpoint)
- [https://www.geeksforgeeks.org/difference-between-http-get-and-post-methods/](https://www.geeksforgeeks.org/difference-between-http-get-and-post-methods/)
- [https://danielmiessler.com/study/difference-between-uri-url/](https://danielmiessler.com/study/difference-between-uri-url/)
- [https://www.hostinger.com/tutorials/uri-vs-url](https://www.hostinger.com/tutorials/uri-vs-url)
