### ISSUE TITLE
Hello World 만들기

### ISSUE THREAD

**Issue by f-lab-robert** [f-lab-edu/Daily#9]
**[ Context ]**
1. Hello World 를 반환하는 Get API 를 만든다.
2. Database 와 연결을 하는 설정을 한다. ( application.yaml ) 

**[ Definition of done ]**
1. application.yaml 을 파일에 db 정보 입력해서 SpringBoot 에서 접근이 가능한지 확인
2. endpoint : "/ping" 을 get 요청하면 pong 이라는 응답이 나와야 한다. controller 와 service 를 1개씩 작성
3. application.yaml 을 github 에 올릴 때 제거해주세요. ( .gitignore )

**Comment by f-lab-robert** [comment]
```
@GetMapping("/ping")
public String pong(){
   return PongService.pong();
}
```

**Comment by erinleeme** [comment]
1. localhost:8080 접속 시 HelloWorld 확인
![스크린샷 2023-05-18 오전 12 03 04(2)](https://github.com/f-lab-edu/Daily/assets/87467958/fdf23048-4583-4049-a9e7-4a105a1daf24)

2. localhost:8080/ping 로 접속 시 pong! 확인
![스크린샷 2023-05-18 오전 12 05 31(2)](https://github.com/f-lab-edu/Daily/assets/87467958/42d04b4c-e8f1-4528-9f69-38028d049f7b)

**Comment by kwj0318** [comment]
RestController 와 Controller 차이 학습 및 RestController 구현
